version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: ["test.wav"] # ENTRYPOINT used to specify the command to run when the container starts

  test:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    entrypoint: []  # Overrides ENTRYPOINT from Dockerfile
    command: ["pytest", "-v", "test_transcribe.py"]